Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OnlineBookstore.Models;
namespace SportsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        //used to create summary
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using OnlineBookstore.Models;

namespace OnlineBookstore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IBookstoreRepository repository;

        //Constructor
        public NavigationMenuViewComponent (IBookstoreRepository r)
        {
            repository = r;
        }

        //Drop partial view
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookCategory.cshtml
@model Book

<!--Partial view containing the inside of the foreach loop in Index-->
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            Title: @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <p>Author: @Model.AuthFirstName @Model.AuthLastName</p>
            </span>
        </h4>
        <p>Publisher: @Model.Publisher</p>
        <p>ISBN: @Model.ISBN</p>
        <p>Classification: @Model.Classification</p>
        <p>Category: @Model.Category</p>
        <p>Price: @("$" + Model.Price)</p>
        <p>Number of Pages: @Model.NumPages</p>
    </div>


    <form id="@Model.BookId" asp-page="/ShoppingCart" method="post">
        <input type="hidden" asp-for="BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Title
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">Add to Cart</button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineBookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/6493d9a2ec.js" crossorigin="anonymous"></script>
</head>
<body>
    <!--Adds cart summary-->
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Hami Reads</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="motto" class="col-2">
            <h1>A Book A Day</h1>
            <!--Nav bar with various categories-->
            <vc:navigation-menu />
        </div>
        <div class="col-10">
            <!--Html views will  go here-->
            @RenderBody()
        </div>
    </div>


</body>
</html>